#include "image_object.hpp"
#include "package.hpp"
#include <type_traits>
#include <vector>
namespace srhd_awa::platform::image_object {namespace{bool F(std::string*e,const char*s){if(e)*e=s;return false;}}
std::int32_t PortableImageObject::natural_width()const{return std::visit([](const auto&v)->std::int32_t{using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::monostate>)return 0;else return v.width();},data_);}std::int32_t PortableImageObject::natural_height()const{return std::visit([](const auto&v)->std::int32_t{using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::monostate>)return 0;else return v.height();},data_);}
std::size_t PortableImageObject::resident_bytes()const{return std::visit([](const auto&v)->std::size_t{using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::monostate>)return 0;else return v.resident_bytes();},data_);}
bool PortableImageObject::Load(Kind kind,const std::string& resource,const std::string& option,std::string* error){data_=std::monostate{};if(!package_)return F(error,"image object package is null");const auto*entry=package_->Resolve(resource);std::vector<std::uint8_t> bytes;if(!entry||!package_->ReadPayload(*entry,&bytes,error))return false;bool ok=false;if(kind==Kind::Simple){simple_bitmap_cpu::SimpleBitmap b;ok=b.Load(bytes.data(),static_cast<std::int32_t>(bytes.size()),option=="RGBA",error);if(ok)data_=std::move(b);}else if(kind==Kind::Trans){trans_bitmap_cpu::TransBitmap b;ok=b.Load(bytes.data(),static_cast<std::int32_t>(bytes.size()),option,error);if(ok)data_=std::move(b);}else{alpha_bitmap_cpu::AlphaBitmap b;ok=b.Load(bytes.data(),static_cast<std::int32_t>(bytes.size()),error);if(ok)data_=std::move(b);}if(!ok)return false;kind_=kind;resource_=resource;if(id_.empty())id_="image-object:"+resource; if(client_width_<=0)client_width_=natural_width();if(client_height_<=0)client_height_=natural_height();return true;}
bool PortableImageObject::DrawFramebuffer(std::uint16_t*p,std::int32_t w,std::int32_t h,std::int32_t pitch,const okgf_rle_bridge::Rect&clip,std::string*e)const{if(!loaded()||!p||w<=0||h<=0||pitch<w)return F(e,"invalid image object framebuffer");if(!visible_)return true;const okgf_rle_bridge::Rect bounds{x_-origin_x_,y_-origin_y_,x_-origin_x_+client_width_,y_-origin_y_+client_height_};const auto plan=image_layout::MakePlan(bounds,clip,natural_width(),natural_height(),x_mode_,y_mode_);if(!plan.supported)return true;for(const auto&t:plan.tiles){bool ok=std::visit([&](const auto&v){using T=std::decay_t<decltype(v)>;if constexpr(std::is_same_v<T,std::monostate>)return false;else if constexpr(std::is_same_v<T,alpha_bitmap_cpu::AlphaBitmap>)return v.Draw(p,w,h,pitch,t.x,t.y,clip,e);else return v.Draw(p,w,h,pitch,t.x,t.y,half_alpha_,clip,e);},data_);if(!ok)return false;}return true;}
bool PortableImageObject::HitTest(std::int32_t px,std::int32_t py,std::string*e)const{if(!loaded()||!visible_||kind_!=Kind::Alpha)return false;const okgf_rle_bridge::Rect bounds{x_-origin_x_,y_-origin_y_,x_-origin_x_+client_width_,y_-origin_y_+client_height_};if(px<bounds.left||px>=bounds.right||py<bounds.top||py>=bounds.bottom)return false;const auto plan=image_layout::MakePlan(bounds,bounds,natural_width(),natural_height(),x_mode_,y_mode_);std::uint16_t pixel{};const okgf_rle_bridge::Rect one{0,0,1,1};for(const auto&t:plan.tiles){auto&alpha=std::get<alpha_bitmap_cpu::AlphaBitmap>(data_);if(!alpha.Draw(&pixel,1,1,1,t.x-px,t.y-py,one,e))return false;if(pixel)return true;}return false;}
}  // namespace srhd_awa::platform::image_object
