#include "gi_format0_cpu.hpp"
#include "runtime_settings_slice.hpp"
#include "startup_slice.hpp"
#include "types/GR_gi.hpp"
#include "units/EC_Buf.hpp"
#include "units/EC_Cache.hpp"
#include "units/EC_Data.hpp"
#include "units/EC_File.hpp"
#include "units/GR_Main.hpp"
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>
namespace {using namespace srhd_awa::platform::gi_format0_cpu;struct C{pas::WideString k;std::string t,f;};std::string N(const pas::WideString&v){return static_cast<pas::AnsiString>(v).c_str();}void W(EC_Data::TDataEC*r,const pas::WideString&p,std::vector<C>*o){for(auto*e=r?r->FirstEntry:nullptr;e;e=e->Next){auto q=p.length()?pas::concat_wide({p,u"."_wref.get(),e->Name}):e->Name;if(e->Kind==EC_Data::dekFile){std::string f;if(e->SharedFileRef&&e->SharedFileRef->FileRef)f=N(e->SharedFileRef->FileRef->FileName);o->push_back({q,N(q),f});}else if(e->Kind==EC_Data::dekSubtree)W(e->ChildData,q,o);}}
std::uint64_t F(const void*d,size_t n){auto*p=(const unsigned char*)d;std::uint64_t r=1469598103934665603ull;while(n--)r=(r^*p++)*1099511628211ull;return r;}std::uint32_t R(const void*d,size_t n){auto*p=(const unsigned char*)d;std::uint32_t r=~0u;while(n--){r^=*p++;for(int b=0;b<8;b++)r=(r>>1)^((r&1)?0xedb88320u:0);}return~r;}bool E(const Metadata&a,const Metadata&b){return a.version==b.version&&a.left==b.left&&a.top==b.top&&a.right==b.right&&a.bottom==b.bottom&&a.width==b.width&&a.height==b.height&&a.plane_count==b.plane_count&&a.clip_rect_count==b.clip_rect_count&&a.red_mask==b.red_mask&&a.green_mask==b.green_mask&&a.blue_mask==b.blue_mask&&a.alpha_mask==b.alpha_mask;}}
int main(int ac,char**av){if(ac!=3)return 2;std::filesystem::path u(av[2]);std::error_code ec;std::filesystem::remove_all(u,ec);srhd_awa::platform::startup_slice::State st;std::string er;if(!srhd_awa::platform::startup_slice::Initialize(&st,av[1],u.string(),(u/"gr.log").string(),&er)||!srhd_awa::platform::runtime_settings_slice::Initialize(&er)){std::fprintf(stderr,"%s\n",er.c_str());return 1;}std::vector<C>v;W(GR_Main::CacheDataRoot,pas::WideString(),&v);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.t<b.t;});int gi=0,valid=0,fmt[7]={},other=0;C rgb,copy;for(auto&x:v){EC_Buf::TBufEC*q=nullptr;try{q=GR_Main::GlobalCache->OpenDataBuffer(x.k);if(q&&q->DataSize>=2&&((unsigned char*)q->Data)[0]=='g'&&((unsigned char*)q->Data)[1]=='i'){++gi;GR_gi::TgiHeaderGR h{};if(q->DataSize>=64){std::memcpy(&h,q->Data,64);if(h.Version==1&&h.PlaneCount>=1&&h.ClipRectCount>=0&&(std::uint64_t)64+(std::uint64_t)h.PlaneCount*32<=(std::uint64_t)q->DataSize)++valid;if(h.Format>=0&&h.Format<=6)++fmt[h.Format];else ++other;if(h.Format==0){Metadata m{};CpuImage a;if(Decode(q->Data,q->DataSize,&m,&a,&er)==Status::Ok){if(m.alpha_mask==0&&rgb.t.empty())rgb=x;if(m.alpha_mask!=0&&copy.t.empty())copy=x;}}}}}catch(...){}pas::free(q);}C chosen=rgb.t.empty()?copy:rgb;std::printf("files=%zu gi=%d valid=%d format0=%d format1=%d format2=%d format3=%d format4=%d format5=%d format6=%d other=%d\n",v.size(),gi,valid,fmt[0],fmt[1],fmt[2],fmt[3],fmt[4],fmt[5],fmt[6],other);bool ok=!chosen.t.empty();if(ok){EC_Buf::TBufEC*q=nullptr;try{q=GR_Main::GlobalCache->OpenDataBuffer(chosen.k);Metadata a{},b{};CpuImage x,y;ok=q&&Decode(q->Data,q->DataSize,&a,&x,&er)==Status::Ok&&Decode(q->Data,q->DataSize,&b,&y,&er)==Status::Ok&&E(a,b)&&x.pixels==y.pixels;if(ok)std::printf("key=%s file=%s source_size=%d source_crc32=%08x source_fnv64=%016llx version=%d format=0 planes=%d clips=%d masks=%08x,%08x,%08x,%08x bounds=%d,%d,%d,%d decoded=%dx%d bpp=%d pitch=%d decoded_bytes=%zu pixel_crc32=%08x pixel_fnv64=%016llx widescreen_fixups=NOT_ENTERED\n",chosen.t.c_str(),chosen.f.c_str(),q->DataSize,R(q->Data,q->DataSize),(unsigned long long)F(q->Data,q->DataSize),a.version,a.plane_count,a.clip_rect_count,a.red_mask,a.green_mask,a.blue_mask,a.alpha_mask,a.left,a.top,a.right,a.bottom,x.width,x.height,x.bytes_per_pixel,x.pitch,x.pixels.size(),R(x.pixels.data(),x.pixels.size()),(unsigned long long)F(x.pixels.data(),x.pixels.size()));x.Clear();y.Clear();}catch(...){ok=false;}pas::free(q);}srhd_awa::platform::runtime_settings_slice::Shutdown();srhd_awa::platform::startup_slice::Shutdown(&st);std::filesystem::remove_all(u,ec);return ok?0:1;}