#include "gi_format0_cpu.hpp"
#include "types/GR_gi.hpp"
#include <climits>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
using namespace srhd_awa::platform::gi_format0_cpu;
namespace {
constexpr int W=2,H=2;constexpr std::size_t O=96;
std::vector<unsigned char> M(bool a){std::vector<unsigned char>b(O+W*H*(a?4:2));GR_gi::TgiHeaderGR h{};h.Magic[0]='g';h.Magic[1]='i';h.Version=1;h.Bounds.Right=W;h.Bounds.Bottom=H;h.Format=0;h.PlaneCount=1;h.AlphaMask=a?0xff000000u:0;GR_gi::TgiPlaneGR p{};p.DataOffset=O;p.DataSize=b.size()-O;std::memcpy(b.data(),&h,sizeof h);std::memcpy(b.data()+64,&p,sizeof p);if(a){const unsigned char q[]={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};std::memcpy(b.data()+O,q,sizeof q);}else{const unsigned short q[]={0,0xffff,0xf800,0x07e0};std::memcpy(b.data()+O,q,sizeof q);}return b;}
std::uint32_t C(const std::vector<std::uint8_t>&v){std::uint32_t c=~0u;for(auto b:v){c^=b;for(int n=0;n<8;++n)c=(c>>1)^((c&1)?0xedb88320u:0);}return~c;}std::uint64_t F(const std::vector<std::uint8_t>&v){std::uint64_t h=1469598103934665603ull;for(auto b:v)h=(h^b)*1099511628211ull;return h;}
bool Z(const CpuImage&i){return !i.width&&!i.height&&!i.pitch&&!i.bytes_per_pixel&&i.pixels.empty();}bool D(const std::vector<unsigned char>&s,Metadata*m,CpuImage*i){std::string e;return Decode(s.data(),s.size(),m,i,&e)==Status::Ok;}bool R(std::vector<unsigned char>s,const char*l){CpuImage i;i.width=i.height=i.pitch=i.bytes_per_pixel=99;i.pixels={1};std::string e;if(Decode(s.empty()?nullptr:s.data(),s.size(),nullptr,&i,&e)==Status::Ok||!Z(i)){std::printf("corrupt accepted: %s\n",l);return false;}return true;}
GR_gi::TgiHeaderGR G(const std::vector<unsigned char>&s){GR_gi::TgiHeaderGR h{};std::memcpy(&h,s.data(),sizeof h);return h;}void G(std::vector<unsigned char>*s,const GR_gi::TgiHeaderGR&h){std::memcpy(s->data(),&h,sizeof h);}GR_gi::TgiPlaneGR P(const std::vector<unsigned char>&s){GR_gi::TgiPlaneGR p{};std::memcpy(&p,s.data()+64,sizeof p);return p;}void P(std::vector<unsigned char>*s,const GR_gi::TgiPlaneGR&p){std::memcpy(s->data()+64,&p,sizeof p);}
}
int main(){const unsigned char e[]={0,0,0,255,248,252,248,255,0,0,248,255,0,252,0,255};for(bool a:{false,true}){auto s=M(a);Metadata m,n;CpuImage x,y;if(!D(s,&m,&x)||!D(s,&n,&y)||x.width!=W||x.height!=H||x.pitch!=8||x.bytes_per_pixel!=4||x.pixels!=y.pixels||m.version!=n.version||m.left!=n.left||m.top!=n.top||m.right!=n.right||m.bottom!=n.bottom||m.width!=n.width||m.height!=n.height||m.plane_count!=n.plane_count||m.clip_rect_count!=n.clip_rect_count||m.red_mask!=n.red_mask||m.green_mask!=n.green_mask||m.blue_mask!=n.blue_mask||m.alpha_mask!=n.alpha_mask)return 1;if((!a&&std::memcmp(x.pixels.data(),e,16))||(a&&std::memcmp(x.pixels.data(),s.data()+O,16)))return 1;if ((a && (C(x.pixels)!=0x094c80f1u || F(x.pixels)!=0xa069b9bf124863c3ull)) || (!a && (C(x.pixels)!=0xf8a05355u || F(x.pixels)!=0x27d6eb722a47841bull))) return 1;}if(!R({},"empty"))return 1;auto b=M(false);auto x=b;x.resize(63);if(!R(x,"truncated header"))return 1;x=b;auto h=G(x);h.Magic[0]='x';G(&x,h);if(!R(x,"magic"))return 1;x=b;h=G(x);h.Version=2;G(&x,h);if(!R(x,"version"))return 1;x=b;h=G(x);h.Format=1;G(&x,h);if(!R(x,"format"))return 1;x=b;h=G(x);h.Bounds.Right=0;G(&x,h);if(!R(x,"zero width"))return 1;x=b;h=G(x);h.Bounds.Bottom=0;G(&x,h);if(!R(x,"zero height"))return 1;x=b;h=G(x);h.Bounds.Left=2;h.Bounds.Right=1;G(&x,h);if(!R(x,"inverted bounds"))return 1;x=b;h=G(x);h.Bounds.Left=INT_MIN;h.Bounds.Right=INT_MAX;G(&x,h);if(!R(x,"int extremes"))return 1;x=b;h=G(x);h.Bounds.Right=20000;h.Bounds.Bottom=20000;G(&x,h);if(!R(x,"limit"))return 1;x=b;h=G(x);h.PlaneCount=-1;G(&x,h);if(!R(x,"negative planes"))return 1;x=b;h=G(x);h.PlaneCount=0;G(&x,h);if(!R(x,"zero planes"))return 1;x=b;h=G(x);h.PlaneCount=2;G(&x,h);x.resize(95);if(!R(x,"truncated plane table"))return 1;x=b;auto p=P(x);p.DataOffset=-1;P(&x,p);if(!R(x,"negative offset"))return 1;x=b;p=P(x);p.DataOffset=0;P(&x,p);if(!R(x,"zero offset"))return 1;x=b;p=P(x);p.DataOffset=1000;P(&x,p);if(!R(x,"offset outside"))return 1;x=b;p=P(x);p.DataSize=-1;P(&x,p);if(!R(x,"negative size"))return 1;x=b;p=P(x);p.DataOffset=100;P(&x,p);if(!R(x,"payload outside"))return 1;x=b;p=P(x);p.DataSize=7;P(&x,p);if(!R(x,"short payload"))return 1;x=b;h=G(x);h.ClipRectCount=1;h.ClipRectTableOffset=1000;G(&x,h);if(!R(x,"clip offset"))return 1;x=b;h=G(x);h.ClipRectCount=INT_MAX;h.ClipRectTableOffset=0;G(&x,h);if(!R(x,"clip range"))return 1;std::puts("GI FORMAT0 CPU PASS");}